version: '2.0'

services:

#---------------------------#
###### work  container ######
#---------------------------#

  workspace:
    build:
      context: ./workspace
    tty: true

#---------------------------#
##### php-fpm container #####
#---------------------------#

  php-fpm:
    build:
      context: ./php-fpm
    ports:
      - "9000"
    volumes:
      - ./logs/php-fpm:/var/log/
      - ./workspace/application:/var/www

#---------------------------#
###### nginx container ######
#---------------------------#

  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM=php-fpm
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./workspace/application:/var/www
    ports:
      - "80:80"
    links:
      - php-fpm

#---------------------------#
###### redis  container #####
#---------------------------#

  redis:
    build: ./redis
    volumes:
      - ./data/redis:/data
      - ./redis/conf:/etc/reids
    ports:
      - "6379:6379"