version: '2.0'

services:

#---------------------------#
###### work  container ######
#---------------------------#

  workspace:
    build:
      context: ./workspace
    tty: true

#---------------------------#
##### php-fpm container #####
#---------------------------#

  php-fpm:
    build:
      context: ./php-fpm
    ports:
      - "9000"
    volumes:
      - ./logs/php-fpm:/var/log/
      - ./workspace/application:/var/www

#---------------------------#
###### nginx container ######
#---------------------------#

  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM=php-fpm
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./workspace/application:/var/www
    ports:
      - "80:80"
    links:
      - php-fpm

#---------------------------#
###### redis  container #####
#---------------------------#

  redis:
    build: ./redis
    volumes:
      - ./data/redis:/data
      - ./redis/conf:/etc/reids
    ports:
      - "6379:6379"

#---------------------------#
###### mysql  container #####
#---------------------------#

  mysql:
    build:
      context: ./mysql
      args:
          - MYSQL_DATABASE=homestead
          - MYSQL_USER=homestead
          - MYSQL_PASSWORD=secret
          - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    ports:
      - "3306:3306"

#--------------------------------#
###### phpMyAdmin  container #####
#--------------------------------#

  phpmyadmin:
    build: ./phpmyadmin
    environment:
        PMA_ARBITRARY: 1
        MYSQL_USER: homestead
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: root
    ports:
        - "8080:80"
    links:
        - "mysql:db"

#--------------------------------#
######     Volumes Setup     #####
#--------------------------------#

volumes:
    mysql:
        driver: "local"
    phpmyadmin:
        driver: "local"
    sessions:
        driver: "local"
